project_name: terraform-provider-ims-cloud
version: 2
release:
  github:
    owner: ims-network
    name: terraform-provider-ims-cloud

builds:
  - id: terraform-provider-ims-cloud
    main: .
    binary: terraform-provider-ims-cloud
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - id: archive
    format: tar.gz
    builds:
      - terraform-provider-ims-cloud
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  extra_files:
    - glob: dist/*.zip
    - glob: dist/*.tar.gz

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - '--batch'
      - '--pinentry-mode'
      - loopback
      - '--sign'
      - '--detach-sign'
      - '--armor'
      - '--output'
      - '${artifact}.sig'
      - '${artifact}'
    env:
      - GPG_FINGERPRINT

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github
